### ISSUE TITLE
svg2json with-gimp.svg image.jpg doesn't actually create a with-gimp.json file?

### ISSUE THREAD

**Issue by wan-andrea** [Affonso-Gui/svglabel#7]
I followed the setup instructions and ran the command svg2json with-gimp.svg image.jpg but it doesn't actually create a with-gimp.json file anywhere I can see. Obviously, when trying to run labelme with-gimp.json, it results in an error that says "no such file: with-gimp.json". Any ideas why this might be happening? Thanks!

**Comment by Affonso-Gui** [comment]
Hello,

It seems like we had a missing dependency: a91d20079b8dd2be53c106de16f82fbb19dd31af
Hopefully re-running from the `pip install -e svglabel/` (and maybe re-opening the terminal) should solve it!

**Comment by wan-andrea** [comment]
Hi, thanks for checking. I re-installed and re-opened the terminal. Running "svg2json with-gimp.svg image.jpg" still doesn't do anything for me, but it does look like if I call the function in the Python script like this...
![image](https://github.com/user-attachments/assets/c6f59cd5-389e-4511-bbe8-ccbd346f8c76)

It does make a file:
![image](https://github.com/user-attachments/assets/cad4d6a2-379d-496e-8282-b146b165d53e)

The file, however, is not identifiable by Labelme:
![image](https://github.com/user-attachments/assets/5c07cd7a-b6a5-414e-a26e-bb5e04f432f3)

I do wonder if it has something to do with different versions of Labelme. Do you have any idea what version you might have used when making this? Cheers

**Comment by Affonso-Gui** [comment]
Hello,

Maybe the command was not added correctly to the path?
Could you give me more details on your environment (os, python version), and any error messages?

> but it does look like if I call the function in the Python script like this...

The second argument should be the original image file.
So in this case:
```
svg2json("examples/with-gimp.svg", "examples/image.jpg")
```
